module.exports = {
  preset: 'jest-expo',
  roots: ['<rootDir>/tests'],
  testMatch: ['**/?(*.)+(test).[jt]s?(x)'],
  setupFilesAfterEnv: ['<rootDir>/tests/jest.setup.ts'],
  collectCoverageFrom: [
    'app/**/*.{ts,tsx,js,jsx}',
    'src/**/*.{ts,tsx,js,jsx}',
    'components/**/*.{ts,tsx,js,jsx}',
    'constants/**/*.{ts,tsx,js,jsx}',
    '!tests/**/*',
    '!src/testing/**/*',
    '!src/**/__tests__/**',
    '!src/**/*.test.*',
    '!src/**/*.spec.*',
    '!src/**/*.mock.*',
    '!src/**/*.generated.*',
    '!src/**/generated/**',
    '!**/*.d.ts',
    '!**/*.web.ts',
    '!**/*.web.tsx',
    '!components/useClientOnlyValue.ts',
    '!components/useClientOnlyValue.web.ts',
    '!app/+html.tsx',
    '!app/lock.tsx',
    '!app/(app)/_layout.tsx',
    '!app/(app)/(tabs)/calendar.tsx',
    '!app/(app)/(tabs)/settings.tsx',
    '!app/(app)/(tabs)/insights.tsx',
    '!app/(app)/(tabs)/today.tsx',
    '!app/(app)/backup/export.tsx',
    '!app/(app)/backup/restore.tsx',
    '!app/(app)/calendar/about-estimates.tsx',
    '!app/(app)/calendar/day/[date].tsx',
    '!app/(app)/calendar/history.tsx',
    '!app/(app)/import/index.tsx',
    '!app/(app)/import/review.tsx',
    '!app/(app)/import/complete.tsx',
    '!app/(app)/import/source/[source].tsx',
    '!app/(app)/insights/condition/[conditionKey].tsx',
    '!app/(app)/insights/cycle-pattern.tsx',
    '!app/(app)/insights/ttc.tsx',
    '!app/(app)/privacy.tsx',
    '!app/(app)/subscribe.tsx',
    '!app/(app)/settings/_layout.tsx',
    '!app/(app)/settings/feedback.tsx',
    '!app/(app)/settings/language.tsx',
    '!app/(app)/settings/data.tsx',
    '!app/(app)/settings/delete-data.tsx',
    '!app/(app)/settings/privacy-lock.tsx',
    '!app/(app)/settings/reminders.tsx',
    '!app/(app)/settings/subscription.tsx',
    '!app/(app)/settings/ttc-setup.tsx',
    '!app/(onboarding)/basics.tsx',
    '!app/(onboarding)/completion.tsx',
    '!app/(onboarding)/cycle-length.tsx',
    '!app/(onboarding)/cycle-variability.tsx',
    '!app/(onboarding)/goals.tsx',
    '!app/(onboarding)/last-period-start.tsx',
    '!app/(onboarding)/paywall.tsx',
    '!app/(onboarding)/period-length.tsx',
    '!app/(onboarding)/privacy.tsx',
    '!app/(onboarding)/setup-later.tsx',
    '!app/(onboarding)/start-path.tsx',
    '!app/(onboarding)/symptom-logging.tsx',
    '!app/(onboarding)/ttc.tsx',
    '!app/(onboarding)/ttc-preset.tsx',
    '!app/(onboarding)/ttc-expectations.tsx',
    '!app/(onboarding)/ttc-setup.tsx',
    '!app/(onboarding)/welcome.tsx',
    '!app/(onboarding)/import/source/[source].tsx',
    '!src/features/feedback/interactionFeedbackNative.ts',
    '!src/features/review/storeReviewNative.ts',
    '!src/localization/localizationNative.ts',
    '!src/features/app-shell/copy.ts',
  ],
  watchman: false,
  coverageThreshold: {
    global: {
      lines: 95,
      statements: 95,
      functions: 95,
    },
  },
  coveragePathIgnorePatterns: [
    '<rootDir>/app/\\(app\\)/settings/_layout\\.tsx$',
    '<rootDir>/src/features/feedback/interactionFeedbackNative\\.ts$',
    '<rootDir>/src/features/review/storeReviewNative\\.ts$',
    '<rootDir>/src/localization/localizationNative\\.ts$',
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(.pnpm|(jest-)?react-native|@react-native(-community)?|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|expo-router|@react-navigation/.*|react-navigation|react-native-svg|@sentry/react-native|native-base|@noble/ciphers|@noble/hashes|expo-iap))',
  ],
};
